services:
  fedow_memcached:
    image: memcached:1.6

  fedow_django:
    build: 
      context: ..
      dockerfile: fedow/Dockerfile    # car le context de ce Dockerfile doit être la racine du dépot
    env_file: .env                    # relatif à ce fichier
    command: ["bash", "start_prod.sh"]
    volumes:
      - fedow_static:/home/fedow/Fedow/www

  fedow_nginx:
    image: nginx:1.30
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d    # volume BIND 
      - fedow_static:/www
volumes:
  fedow_static:


