services:
  fedow_memcached:
    image: memcached:1.6

  fedow_django:
    build:                          # car le context de ce Dockerfile doit être la racine du dépot
      context: ..
      dockerfile: fedow/Dockerfile    
    env_file: .env                    # relatif à ce fichier
    command: ["bash", "start_prod.sh"]
    volumes:
      - fedow_static:/home/fedow/Fedow/www
    networks:
      - default
      - tibillet_backend

  fedow_nginx:
    image: nginx:1.30
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d    # volume BIND 
      - fedow_static:/www
volumes:
  fedow_static:

networks:
  default:
  tibillet_backend:
    external: true

