services:
  fedow_memcached:
    image: memcached:1.6

  fedow_django:
    build:                          # car le context de ce Dockerfile doit être la racine du dépot
      context: .
      dockerfile: fedow/Dockerfile
    depends_on:
      - fedow_memcached
    env_file: ./fedow/.env.test
    volumes:
      - fedow_db:/home/fedow/Fedow/database
      - fedow_static:/home/fedow/Fedow/www
      - fedow_logs:/home/fedow/Fedow/logs
      - fedow_backup:/home/fedow/Fedow/backup
    links:
      - fedow_memcached:memcached
    command: ["bash", "start_prod.sh"]

  fedow_nginx:
    build:
      context: fedow/nginx
    depends_on:
      - fedow_django
    volumes:
      - fedow_static:/www 
    ports:
      - 8000:80
      
  lespass_postgres:
    image: postgres:13-bookworm
    env_file: ./lespass/.env.test
    volumes:
      - lespass_db:/var/lib/postgresql/data

  lespass_django:
    build:              # car le context de ce Dockerfile doit être la racine du dépot
      context: .
      dockerfile: lespass/Dockerfile
    depends_on:
      - lespass_postgres
      - lespass_memcached
    env_file: ./lespass/.env.test
    environment:
      - POSTGRES_HOST=lespass_postgres
    links:
      - lespass_memcached:memcached
    volumes:
      - lespass_static:/DjangoFiles/www
      - lespass_logs:/DjangoFiles/logs
      - lespass_backup:/DjangoFiles/Backup
    command: ["bash", "start_prod.sh"]

  lespass_redis:
    image: redis:7.2-bookworm

  lespass_celery:
    build:              # on utilise également l'image de Lespass
      context: .
      dockerfile: lespass/Dockerfile
    depends_on:
      - lespass_postgres
      - lespass_redis
      - lespass_memcached
    env_file: ./lespass/.env.test
    environment:
      - POSTGRES_HOST=lespass_postgres
      - CELERY_BROKER=redis://lespass_redis:6379/0
    links:
      - lespass_memcached:memcached
    command: "poetry run celery -A TiBillet worker -l INFO -B --concurrency=6"

  lespass_memcached:
    image: memcached:1.6

  lespass_nginx:
    build:
      context: ./lespass/nginx
    depends_on:
      - lespass_django
    volumes:
      - lespass_static:/www
    ports:
      - 8001:80

volumes:
  fedow_db:
  fedow_static:
  fedow_logs:
  fedow_backup:
  lespass_db:
  lespass_static:
  lespass_logs:
  lespass_backup: