services:
  fedow_memcached:
    image: memcached:1.6

  fedow_django:
    build:
      context: .
      dockerfile: fedow/Dockerfile
    depends_on:
      - fedow_memcached
    env_file: ./fedow/.env.test
    environment:
      - FEDOW_DOMAIN=
      - FEDOW_SECRET_KEY=
      - FERNET_KEY=
      - FEDOW_STRIPE_KEY=
      - FEDOW_STRIPE_KEY_TEST=
      - FEDOW_STRIPE_ENDPOINT_SECRET_TEST=
      - FEDOW_TEST_STRIPE_CONNECT_ACCOUNT=
      - FEDOW_STRIPE_TEST=
      - FEDOW_DEBUG=
    volumes:
      - fedow_db:/home/fedow/Fedow/database
      - fedow_static:/home/fedow/Fedow/www
      - fedow_logs:/home/fedow/Fedow/logs
      - fedow_backup:/home/fedow/Fedow/backup
    links:
      - fedow_memcached:memcached
    command: ["bash", "start_prod.sh"]

  fedow_nginx:
    build:
      context: fedow/nginx
    depends_on:
      - fedow_django
    volumes:
      - fedow_static:/www

  lespass_postgres:
    image: postgres:13-bookworm
    env_file: ./lespass/.env.test
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    volumes:
      - lespass_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  lespass_django:
    build:
      context: .
      dockerfile: lespass/Dockerfile
    depends_on:
      lespass_postgres:
        condition: service_healthy
      lespass_redis:
        condition: service_started
      lespass_memcached:
        condition: service_started
    env_file: ./lespass/.env.test
    environment:
      - DJANGO_SECRET=
      - DOMAIN=
      - SUB=
      - META=
      - PUBLIC=
      - ADMIN_EMAIL=
      - FEDOW_DOMAIN=
      - FERNET_KEY=
      - STRIPE_KEY_TEST=
      - STRIPE_ENDPOINT_SECRET_TEST=
      - TEST_STRIPE_CONNECT_ACCOUNT=
      - STRIPE_TEST=
      - EMAIL_HOST=
      - EMAIL_PORT=
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=lespass_postgres
      - CELERY_BROKER=redis://lespass_redis:6379/0
    links:
      - lespass_memcached:memcached
    volumes:
      - lespass_static:/DjangoFiles/www
      - lespass_logs:/DjangoFiles/logs
      - lespass_backup:/DjangoFiles/Backup
    command: ["bash", "start_prod.sh"]

  lespass_redis:
    image: redis:7.2-bookworm

  lespass_celery:
    build:
      context: .
      dockerfile: lespass/Dockerfile
    depends_on:
      lespass_postgres:
        condition: service_healthy
      lespass_redis:
        condition: service_started
      lespass_memcached:
        condition: service_started
    env_file: ./lespass/.env.test
    environment:
      - DJANGO_SECRET=
      - DOMAIN=
      - SUB=
      - META=
      - PUBLIC=
      - ADMIN_EMAIL=
      - FEDOW_DOMAIN=
      - FERNET_KEY=
      - STRIPE_KEY_TEST=
      - STRIPE_ENDPOINT_SECRET_TEST=
      - TEST_STRIPE_CONNECT_ACCOUNT=
      - STRIPE_TEST=
      - EMAIL_HOST=
      - EMAIL_PORT=
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=lespass_postgres
      - CELERY_BROKER=redis://lespass_redis:6379/0
    links:
      - lespass_memcached:memcached
    command: "poetry run celery -A TiBillet worker -l INFO -B --concurrency=6"

  lespass_memcached:
    image: memcached:1.6

  lespass_nginx:
    build:
      context: ./lespass/nginx
    depends_on:
      - lespass_django
    volumes:
      - lespass_static:/www

volumes:
  fedow_db:
  fedow_static:
  fedow_logs:
  fedow_backup:
  lespass_db:
  lespass_static:
  lespass_logs:
  lespass_backup:
