services:
  lespass_postgres:
    image: postgres:13-bookworm
    env_file: .env

  lespass_django:
    build:              # car le context de ce Dockerfile doit être la racine du dépot
      context: ..
      dockerfile: lespass/Dockerfile
    depends_on:
      - lespass_postgres
      - lespass_memcached
    env_file: .env
    environment:
      - POSTGRES_HOST=lespass_postgres
    links:
      - lespass_memcached:memcached
    volumes:
      - ./www:/DjangoFiles/www
    command: ["bash", "start_prod.sh"]


  lespass_redis:
    image: redis:7.2-bookworm

  lespass_celery:
    build:              # on utilise également l'image de Lespass
      context: ..
      dockerfile: lespass/Dockerfile
    depends_on:
      - lespass_postgres
      - lespass_redis
      - lespass_memcached
    env_file: .env
    environment:
      - POSTGRES_HOST=lespass_postgres
      - CELERY_BROKER=redis://lespass_redis:6379/0
    links:
      - lespass_memcached:memcached
    command: "poetry run celery -A TiBillet worker -l INFO -B --concurrency=6"

  lespass_memcached:
    image: memcached:1.6

  lespass_nginx:
    image: nginx:1.30
    depends_on:
      - lespass_django
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d    # volume BIND 
      - ./www:/www                   # on utilise un répertoire du host pour partager les fichiers statiques